# Generated by Django 5.1.9 on 2025-06-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_activate_unaccent_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='revision',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Revision number of the ironcalc model, incremented on each model update.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('fr-fr', 'Français'), ('de-de', 'Deutsch'), ('nl-nl', 'Nederlands'), ('es-es', 'Español')], default=None, help_text='The language in which the user wants to see the interface.', max_length=10, null=True, verbose_name='language'),
        ),
    ]
